# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ab2b25c922b089221dd1692700ef50087e90d0f1b29f409865826f92f098bb0f76645b754864ee0212c84523d1fd4cc10b9ee8978bc4c849783c3ff25125f6aa

test:
  secret_key_base: 396cdbea7f6c711f82716df8f9507778433b756f1d408f1469858a582397041ff603cd105385276daac18615cebb872e9e4432522f0f916580dd8707d7df2dca

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
